// <auto-generated />
using System;
using MVC_Blazor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_Blazor.Migrations
{
    [DbContext(typeof(BancoContext))]
    [Migration("20241031131419_MVC_Blazor")]
    partial class MVC_Blazor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC_Blazor.Model.Curso", b =>
                {
                    b.Property<int>("ID_Curso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Curso"));

                    b.Property<int>("Carga_Horaria")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data_Fim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_Inicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome_Curso")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ID_Curso");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("MVC_Blazor.Model.Inscricao", b =>
                {
                    b.Property<int>("ID_Inscricao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Inscricao"));

                    b.Property<int?>("CursoID_Curso")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Data_Conclusao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Data_Inscricao")
                        .HasColumnType("datetime2");

                    b.Property<int>("ID_Curso")
                        .HasColumnType("int");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.Property<decimal?>("Nota_Final")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Status_Inscricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioID_Usuario")
                        .HasColumnType("int");

                    b.HasKey("ID_Inscricao");

                    b.HasIndex("CursoID_Curso");

                    b.HasIndex("UsuarioID_Usuario");

                    b.ToTable("Inscricoes");
                });

            modelBuilder.Entity("MVC_Blazor.Model.Usuario", b =>
                {
                    b.Property<int>("ID_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Usuario"));

                    b.Property<DateTime>("Data_Criacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Usuario");

                    b.ToTable("Usuarios1");
                });

            modelBuilder.Entity("MVC_Blazor.Model.Inscricao", b =>
                {
                    b.HasOne("MVC_Blazor.Model.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoID_Curso");

                    b.HasOne("MVC_Blazor.Model.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioID_Usuario");

                    b.Navigation("Curso");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
